#!/bin/bash

#beep -f 1400 -l 250

#cd /media/raid/videos/conversion/foyerflat/;
#find -name "* *" -type f | rename 's/ /_/g';

B=$(basename "$1");

OUTPUT=foyerflat
OUTPUTDIR=/media/raid/video/

#1280x720

ffmpeg -i $1 -y -acodec  libfdk_aac -ab 256k -ac 2 -vcodec libx264 -s 1280x720 -b 3000k -r 25 $OUTPUTDIR$OUTPUT.mp4  1>/media/raid/video/conversion/converted/block.txt 2>&1
#720x576
#ffmpeg -i $1 -y -acodec  libfdk_aac -ab 256k -ac 2 -vcodec libx264 -s 720x576 -b 3000k -r 25 $OUTPUTDIR$OUTPUT.mp4  1>/media/raid/video/conversion/converted/block.txt 2>&1

#/usr/local/bin/qt-faststart $OUTPUTDIR$OUTPUT.mp4 $OUTPUTDIR${B%.*}_${OUTPUT}_stream.mp4

#This line moves the moov atom to the beginning of the file for immediate streaming
#/usr/local/bin/qt-faststart $OUTPUTDIR$OUTPUT.mp4 $OUTPUTDIR${OUTPUT}_stream.mp4


#rm $OUTPUTDIR$OUTPUT.mp4

mv $1 /media/raid/videos/conversion/processed/


#beep -f 1000 -l 500
#sh /media/raid/data/bash/mario.sh
