#!/bin/bash

beep -f 1400 -l 250

B=$(basename "$1");

DATER=`date +%Y%m%d_%H%M%S`
DATER=`date +%Y%m%d_%H%M%S`
SETS=h264_1150k_1280x720_15fps
OUTPUT=${B%.*}_${SETS}_${DATER}

OUTPUTDIR=/media/raid/videos/conversion/converted/
OUTPUT2=`date +%Y%m%d_%H%M%S_block`
BLOCKDIR=/media/raid5/video/conversion/converted/block
BLOCK= `block`

ffmpeg -i $1 -y -acodec  libfdk_aac -ab 256k -ac 2 -vcodec libx264 -s 1280x720 -b 950k -r 15 $OUTPUTDIR$OUTPUT.mp4  1>/media/raid/videos/conversion/converted/block.txt 2>&1

#/usr/local/bin/qt-faststart $OUTPUTDIR$OUTPUT.mp4 $OUTPUTDIR${B%.*}_${OUTPUT}_stream.mp4

#This line moves the moov atom to the beginning of the file for immediate streaming
/usr/local/bin/qt-faststart $OUTPUTDIR$OUTPUT.mp4 $OUTPUTDIR${OUTPUT}_stream.mp4


rm $OUTPUTDIR$OUTPUT.mp4

mv $1 /media/raid/videos/conversion/processed/


#beep -f 1000 -l 500
sh /media/raid/data/bash/mario.sh
