#!/bin/bash

beep -f 1400 -l 250

OUTPUT=`date +%Y%m%d_%H%M%S_h264_200k_640x360`
OUTPUTDIR=/media/raid/videos/conversion/converted/

ffmpeg -i $1 -y -acodec  libfdk_aac -ab 96k -ac 2 -vcodec libx264 -s 360x288 -b 200k -preset medium  $OUTPUTDIR$OUTPUT.mp4

mv $1 /media/raid/videos/conversion/processed/

beep -f 1000 -l 500