#!/bin/bash

beep -f 1400 -l 250

B=$(basename "$1");

DATER=`date +%Y%m%d_%H%M%S`
OUTPUT=`date +%Y%m%d_%H%M%S_h264_1100k_720x480_ipad`
SETS=h264_1100k_720x480_ipad
OUTPUT=${B%.*}_${SETS}_${DATER}
OUTPUTDIR=/media/raid/videos/conversion/converted/
OUTPUT2=`date +%Y%m%d_%H%M%S_block`
BLOCKDIR=/media/raid/videos/conversion/converted/block
BLOCK= `block`

#ffmpeg -i $1 -y -acodec  libfdk_aac -ab 256k -ac 2 -vcodec libx264 -s 720x480 -b 500k -r 25 $OUTPUTDIR$OUTPUT.mp4  1>/media/raid/videos/conversion/converted/block.txt 2>&1;
# Original Frame Rate
ffmpeg -i $1 -y -acodec  libfdk_aac -ab 256k -ac 2 -vcodec libx264 -s 720x480 -b 500k -r 29 $OUTPUTDIR$OUTPUT.mp4  1>/media/raid/videos/conversion/converted/block.txt 2>&1;

#This line moves the moov atom to the beginning of the file for immediate streaming
/usr/local/bin/qt-faststart $OUTPUTDIR$OUTPUT.mp4 $OUTPUTDIR${OUTPUT}_stream.mp4


rm $OUTPUTDIR$OUTPUT.mp4

mv $1 /media/raid/videos/conversion/processed/



#beep -f 1000 -l 500
sh /media/raid/data/bash/mario.sh
