#!/bin/bash
beep -f 1400 -l 250

OUTPUT=`date +%Y%m%d_%H%M%S_mp4_3000k_fullsize`
OUTPUTDIR=/media/raid/videos/conversion/converted/

ffmpeg -i $1 -ab 48000 -vcodec mpeg4  -b 3000k $OUTPUTDIR$OUTPUT.mp4
mv $1 /media/raid/videos/conversion/processed/

beep -f 1000 -l 500

