#!/bin/bash

beep -f 1400 -l 250

OUTPUT=`date +%Y%m%d_%H%M%S_200k_360x288`
OUTPUTDIR=/media/raid/videos/conversion/converted/

ffmpeg -i $1 -vcodec libx264 -b 200k -s 360x288 -preset medium $OUTPUTDIR$OUTPUT.mp4

/usr/local/bin/qt-faststart $OUTPUTDIR$OUTPUT.mp4 $OUTPUTDIR${OUTPUT}_stream.mp4

beep -f 1000 -l 500

mv $1 /media/raid/videos/conversion/processed/

